version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spacely_db
      - POSTGRES_USER=spacely_user
      - POSTGRES_PASSWORD=spacelysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
